name: celeba-hq
img_size: 120
channels: 3
t0_bs: 128

task_objects: None

task_sizes: [10, 2, 2, 2, 
             2, 2, 2, 2, 
             2, 2, 2, 2, 
             2, 2, 2, 2]

num_tasks: 16
num_classes: 40

stream_size: 15
test_size: 5
super_size: 1
stream_bs: 1

t0_size: 10
t0_factor: 1.0

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

task_order: [
      ['102', '1027', '103', '104', '1041',
       '1043', '1044', '1047', '1052', '1060'],
      ['1077', '1079'],
      ['108', '1081'],
      ['1087', '1090'],
      ['1093', '1109'],
      ['111', '1112'],
      ['112', '1120'],
      ['1126', '1133'],
      ['1140', '1145'],
      ['1149', '1157'],
      ['1158', '116'],
      ['1191', '121'],
      ['1210', '122'],
      ['1220', '1237'],
      ['124', '125'],
      ['1256', '1262']
]

task_classes: {
            '102': '102',
            '1027': '1027',
            '103': '103',
            '104': '104',
            '1041': '1041',
            '1043': '1043',
            '1044': '1044',
            '1047': '1047',
            '1052': '1052',
            '1060': '1060',
            '1077': '1077',
            '1079': '1079',
            '108': '108',
            '1081': '1081',
            '1087': '1087',
            '1090': '1090',
            '1093': '1093',
            '1109': '1109',
            '111': '111',
            '1112': '1112',
            '112': '112',
            '1120': '1120',
            '1126': '1126',
            '1133': '1133',
            '1140': '1140',
            '1145': '1145',
            '1149': '1149',
            '1157': '1157',
            '1158': '1158',
            '116': '116',
            '1191': '1191',
            '121': '121',
            '1210': '1210',
            '122': '122',
            '1220': '1220',
            '1237': '1237',
            '124': '124',
            '125': '125',
            '1256': '1256',
            '1262': '1262',
            '1268': '1268',
            '1269': '1269',
            '128': '128',
            '1280': '1280',
            '1285': '1285',
            '129': '129',
            '1291': '1291',
            '1293': '1293',
            '1307': '1307',
            '1317': '1317',
            '1330': '1330',
            '1335': '1335',
            '1350': '1350',
            '1351': '1351',
            '1370': '1370',
            '1396': '1396',
            '14': '14',
            '1407': '1407',
            '1427': '1427',
            '1429': '1429',
            '143': '143',
            '1435': '1435',
            '1440': '1440',
            '1452': '1452',
            '146': '146',
            '1507': '1507',
            '1515': '1515',
            '1521': '1521',
            '1531': '1531',
            '1538': '1538',
            '1550': '1550',
            '158': '158',
            '1581': '1581',
            '1584': '1584',
            '1595': '1595',
            '161': '161',
            '162': '162',
            '17': '17',
            '1718': '1718',
            '1730': '1730',
            '175': '175',
            '177': '177',
            '1775': '1775',
            '1781': '1781',
            '179': '179',
            '1796': '1796',
            '180': '180',
            '1800': '1800',
            '181': '181',
            '182': '182',
            '1823': '1823',
            '183': '183',
            '1837': '1837',
            '1838': '1838',
            '1848': '1848',
            '188': '188',
            '1904': '1904',
            '1930': '1930',
            '194': '194',
            '195': '195',
            '196': '196',
            '1965': '1965',
            '1972': '1972',
            '1974': '1974',
            '198': '198',
            '1989': '1989',
            '199': '199',
            '2020': '2020',
            '203': '203',
            '2037': '2037',
            '204': '204',
            '205': '205',
            '206': '206',
            '2076': '2076',
            '208': '208',
            '2116': '2116',
            '2120': '2120',
            '213': '213',
            '2131': '2131',
            '218': '218',
            '2193': '2193',
            '2214': '2214',
            '223': '223',
            '226': '226',
            '228': '228',
            '230': '230',
            '235': '235',
            '2402': '2402',
            '242': '242',
            '2464': '2464',
            '25': '25',
            '251': '251',
            '255': '255',
            '258': '258',
            '26': '26',
            '260': '260',
            '262': '262',
            '263': '263',
            '2632': '2632',
            '267': '267',
            '268': '268',
            '270': '270',
            '2734': '2734',
            '276': '276',
            '277': '277',
            '285': '285',
            '286': '286',
            '289': '289',
            '295': '295',
            '299': '299',
            '301': '301',
            '304': '304',
            '309': '309',
            '314': '314',
            '321': '321',
            '327': '327',
            '329': '329',
            '330': '330',
            '332': '332',
            '334': '334',
            '335': '335',
            '3368': '3368',
            '34': '34',
            '342': '342',
            '343': '343',
            '351': '351',
            '356': '356',
            '360': '360',
            '361': '361',
            '362': '362',
            '366': '366',
            '368': '368',
            '374': '374',
            '376': '376',
            '379': '379',
            '385': '385',
            '3911': '3911',
            '406': '406',
            '407': '407',
            '409': '409',
            '410': '410',
            '422': '422',
            '423': '423',
            '425': '425',
            '437': '437',
            '438': '438',
            '44': '44',
            '440': '440',
            '442': '442',
            '449': '449',
            '45': '45',
            '450': '450',
            '451': '451',
            '452': '452',
            '458': '458',
            '461': '461',
            '469': '469',
            '47': '47',
            '479': '479',
            '481': '481',
            '483': '483',
            '486': '486',
            '49': '49',
            '495': '495',
            '5': '5',
            '501': '501',
            '509': '509',
            '516': '516',
            '521': '521',
            '528': '528',
            '530': '530',
            '532': '532',
            '537': '537',
            '556': '556',
            '559': '559',
            '560': '560',
            '561': '561',
            '562': '562',
            '563': '563',
            '564': '564',
            '571': '571',
            '573': '573',
            '577': '577',
            '578': '578',
            '587': '587',
            '591': '591',
            '593': '593',
            '597': '597',
            '598': '598',
            '603': '603',
            '606': '606',
            '609': '609',
            '615': '615',
            '618': '618',
            '622': '622',
            '624': '624',
            '628': '628',
            '629': '629',
            '63': '63',
            '632': '632',
            '636': '636',
            '649': '649',
            '65': '65',
            '651': '651',
            '664': '664',
            '67': '67',
            '673': '673',
            '674': '674',
            '676': '676',
            '677': '677',
            '678': '678',
            '679': '679',
            '688': '688',
            '698': '698',
            '701': '701',
            '703': '703',
            '716': '716',
            '719': '719',
            '725': '725',
            '731': '731',
            '735': '735',
            '745': '745',
            '746': '746',
            '748': '748',
            '766': '766',
            '77': '77',
            '776': '776',
            '782': '782',
            '785': '785',
            '793': '793',
            '795': '795',
            '80': '80',
            '805': '805',
            '812': '812',
            '816': '816',
            '817': '817',
            '820': '820',
            '840': '840',
            '841': '841',
            '845': '845',
            '846': '846',
            '847': '847',
            '848': '848',
            '851': '851',
            '858': '858',
            '862': '862',
            '864': '864',
            '870': '870',
            '872': '872',
            '878': '878',
            '879': '879',
            '882': '882',
            '894': '894',
            '908': '908',
            '934': '934',
            '945': '945',
            '95': '95',
            '952': '952',
            '953': '953',
            '956': '956',
            '959': '959',
            '968': '968',
            '980': '980',
            '982': '982',
            '99': '99',
            '993': '993',
            '995': '995'
 }