name: places365-easy
img_size: 120
channels: 3
t0_bs: 128

task_objects: None

task_sizes: [10, 1, 1, 1,
             1, 1, 1, 1,
             1, 1, 1]


num_tasks: 11
num_classes: 20

stream_size: 2500
test_size: 100
super_size: 200
stream_bs: 1

t0_size: 10
t0_factor: 1.0

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

task_order: [
            ['Airfield', 'AirplaneCabin', 'AssemblyLine', 'BallPit', 'Cemetery',
             'Arena-Hockey', 'BusInterior', 'Badlands', 'LectureRoom', 'Jacuzzi-Indoor'],
            ['WaterTower'],
            ['GolfCourse'],
            ['Mountain'],
            ['SubwayStation-Platform'],
            ['Glacier'],
            ['Desert-Vegetation'],
            ['Desert-Sand'],
            ['HospitalRoom'],
            ['Underwater-OceanDeep'],
            ['Highway'],
]

task_classes: {
            'airfield': 'Airfield',
            'airplane_cabin': 'AirplaneCabin',
            'airport_terminal': 'AirportTerminal',
            'alcove': 'Alcove',
            'alley': 'Alley',
            'amphitheater': 'Amphitheater',
            'amusement_arcade': 'AmusementArcade',
            'amusement_park': 'AmusementPark',
            'apartment_building-outdoor': 'ApartmentBuilding-Outdoor',
            'aquarium': 'Aquarium',
            'aqueduct': 'Aqueduct',
            'arcade': 'Arcade',
            'arch': 'Arch',
            'archaelogical_excavation': 'ArchaelogicalExcavation',
            'archive': 'Archive',
            'arena-hockey': 'Arena-Hockey',
            'arena-performance': 'Arena-Performance',
            'arena-rodeo': 'Arena-Rodeo',
            'army_base': 'ArmyBase',
            'art_gallery': 'ArtGallery',
            'art_school': 'ArtSchool',
            'art_studio': 'ArtStudio',
            'artists_loft': 'ArtistsLoft',
            'assembly_line': 'AssemblyLine',
            'athletic_field-outdoor': 'AthleticField-Outdoor',
            'atrium-public': 'Atrium-Public',
            'attic': 'Attic',
            'auditorium': 'Auditorium',
            'auto_factory': 'AutoFactory',
            'auto_showroom': 'AutoShowroom',
            'badlands': 'Badlands',
            'bakery-shop': 'Bakery-Shop',
            'balcony-exterior': 'Balcony-Exterior',
            'balcony-interior': 'Balcony-Interior',
            'ball_pit': 'BallPit',
            'ballroom': 'Ballroom',
            'bamboo_forest': 'BambooForest',
            'bank_vault': 'BankVault',
            'banquet_hall': 'BanquetHall',
            'bar': 'Bar',
            'barn': 'Barn',
            'barndoor': 'Barndoor',
            'baseball_field': 'BaseballField',
            'basement': 'Basement',
            'basketball_court-indoor': 'BasketballCourt-Indoor',
            'bathroom': 'Bathroom',
            'bazaar-indoor': 'Bazaar-Indoor',
            'bazaar-outdoor': 'Bazaar-Outdoor',
            'beach': 'Beach',
            'beach_house': 'BeachHouse',
            'beauty_salon': 'BeautySalon',
            'bedchamber': 'Bedchamber',
            'bedroom': 'Bedroom',
            'beer_garden': 'BeerGarden',
            'beer_hall': 'BeerHall',
            'berth': 'Berth',
            'biology_laboratory': 'BiologyLaboratory',
            'boardwalk': 'Boardwalk',
            'boat_deck': 'BoatDeck',
            'boathouse': 'Boathouse',
            'bookstore': 'Bookstore',
            'booth-indoor': 'Booth-Indoor',
            'botanical_garden': 'BotanicalGarden',
            'bow_window-indoor': 'BowWindow-Indoor',
            'bowling_alley': 'BowlingAlley',
            'boxing_ring': 'BoxingRing',
            'bridge': 'Bridge',
            'building_facade': 'BuildingFacade',
            'bullring': 'Bullring',
            'burial_chamber': 'BurialChamber',
            'bus_interior': 'BusInterior',
            'bus_station-indoor': 'BusStation-Indoor',
            'butchers_shop': 'ButchersShop',
            'butte': 'Butte',
            'cabin-outdoor': 'Cabin-Outdoor',
            'cafeteria': 'Cafeteria',
            'campsite': 'Campsite',
            'campus': 'Campus',
            'canal-natural': 'Canal-Natural',
            'canal-urban': 'Canal-Urban',
            'candy_store': 'CandyStore',
            'canyon': 'Canyon',
            'car_interior': 'CarInterior',
            'carrousel': 'Carrousel',
            'castle': 'Castle',
            'catacomb': 'Catacomb',
            'cemetery': 'Cemetery',
            'chalet': 'Chalet',
            'chemistry_lab': 'ChemistryLab',
            'childs_room': 'ChildsRoom',
            'church-indoor': 'Church-Indoor',
            'church-outdoor': 'Church-Outdoor',
            'classroom': 'Classroom',
            'clean_room': 'CleanRoom',
            'cliff': 'Cliff',
            'closet': 'Closet',
            'clothing_store': 'ClothingStore',
            'coast': 'Coast',
            'cockpit': 'Cockpit',
            'coffee_shop': 'CoffeeShop',
            'computer_room': 'ComputerRoom',
            'conference_center': 'ConferenceCenter',
            'conference_room': 'ConferenceRoom',
            'construction_site': 'ConstructionSite',
            'corn_field': 'CornField',
            'corral': 'Corral',
            'corridor': 'Corridor',
            'cottage': 'Cottage',
            'courthouse': 'Courthouse',
            'courtyard': 'Courtyard',
            'creek': 'Creek',
            'crevasse': 'Crevasse',
            'crosswalk': 'Crosswalk',
            'dam': 'Dam',
            'delicatessen': 'Delicatessen',
            'department_store': 'DepartmentStore',
            'desert-sand': 'Desert-Sand',
            'desert-vegetation': 'Desert-Vegetation',
            'desert_road': 'DesertRoad',
            'diner-outdoor': 'Diner-Outdoor',
            'dining_hall': 'DiningHall',
            'dining_room': 'DiningRoom',
            'discotheque': 'Discotheque',
            'doorway-outdoor': 'Doorway-Outdoor',
            'dorm_room': 'DormRoom',
            'downtown': 'Downtown',
            'dressing_room': 'DressingRoom',
            'driveway': 'Driveway',
            'drugstore': 'Drugstore',
            'elevator-door': 'Elevator-Door',
            'elevator_lobby': 'ElevatorLobby',
            'elevator_shaft': 'ElevatorShaft',
            'embassy': 'Embassy',
            'engine_room': 'EngineRoom',
            'entrance_hall': 'EntranceHall',
            'escalator-indoor': 'Escalator-Indoor',
            'excavation': 'Excavation',
            'fabric_store': 'FabricStore',
            'farm': 'Farm',
            'fastfood_restaurant': 'FastfoodRestaurant',
            'field-cultivated': 'Field-Cultivated',
            'field-wild': 'Field-Wild',
            'field_road': 'FieldRoad',
            'fire_escape': 'FireEscape',
            'fire_station': 'FireStation',
            'fishpond': 'Fishpond',
            'flea_market-indoor': 'FleaMarket-Indoor',
            'florist_shop-indoor': 'FloristShop-Indoor',
            'food_court': 'FoodCourt',
            'football_field': 'FootballField',
            'forest-broadleaf': 'Forest-Broadleaf',
            'forest_path': 'ForestPath',
            'forest_road': 'ForestRoad',
            'formal_garden': 'FormalGarden',
            'fountain': 'Fountain',
            'galley': 'Galley',
            'garage-indoor': 'Garage-Indoor',
            'garage-outdoor': 'Garage-Outdoor',
            'gas_station': 'GasStation',
            'gazebo-exterior': 'Gazebo-Exterior',
            'general_store-indoor': 'GeneralStore-Indoor',
            'general_store-outdoor': 'GeneralStore-Outdoor',
            'gift_shop': 'GiftShop',
            'glacier': 'Glacier',
            'golf_course': 'GolfCourse',
            'greenhouse-indoor': 'Greenhouse-Indoor',
            'greenhouse-outdoor': 'Greenhouse-Outdoor',
            'grotto': 'Grotto',
            'gymnasium-indoor': 'Gymnasium-Indoor',
            'hangar-indoor': 'Hangar-Indoor',
            'hangar-outdoor': 'Hangar-Outdoor',
            'harbor': 'Harbor',
            'hardware_store': 'HardwareStore',
            'hayfield': 'Hayfield',
            'heliport': 'Heliport',
            'highway': 'Highway',
            'home_office': 'HomeOffice',
            'home_theater': 'HomeTheater',
            'hospital': 'Hospital',
            'hospital_room': 'HospitalRoom',
            'hot_spring': 'HotSpring',
            'hotel-outdoor': 'Hotel-Outdoor',
            'hotel_room': 'HotelRoom',
            'house': 'House',
            'hunting_lodge-outdoor': 'HuntingLodge-Outdoor',
            'ice_cream_parlor': 'IceCreamParlor',
            'ice_floe': 'IceFloe',
            'ice_shelf': 'IceShelf',
            'ice_skating_rink-indoor': 'IceSkatingRink-Indoor',
            'ice_skating_rink-outdoor': 'IceSkatingRink-Outdoor',
            'iceberg': 'Iceberg',
            'igloo': 'Igloo',
            'industrial_area': 'IndustrialArea',
            'inn-outdoor': 'Inn-Outdoor',
            'islet': 'Islet',
            'jacuzzi-indoor': 'Jacuzzi-Indoor',
            'jail_cell': 'JailCell',
            'japanese_garden': 'JapaneseGarden',
            'jewelry_shop': 'JewelryShop',
            'junkyard': 'Junkyard',
            'kasbah': 'Kasbah',
            'kennel-outdoor': 'Kennel-Outdoor',
            'kindergarden_classroom': 'KindergardenClassroom',
            'kitchen': 'Kitchen',
            'lagoon': 'Lagoon',
            'lake-natural': 'Lake-Natural',
            'landfill': 'Landfill',
            'landing_deck': 'LandingDeck',
            'laundromat': 'Laundromat',
            'lawn': 'Lawn',
            'lecture_room': 'LectureRoom',
            'legislative_chamber': 'LegislativeChamber',
            'library-indoor': 'Library-Indoor',
            'library-outdoor': 'Library-Outdoor',
            'lighthouse': 'Lighthouse',
            'living_room': 'LivingRoom',
            'loading_dock': 'LoadingDock',
            'lobby': 'Lobby',
            'lock_chamber': 'LockChamber',
            'locker_room': 'LockerRoom',
            'mansion': 'Mansion',
            'manufactured_home': 'ManufacturedHome',
            'market-indoor': 'Market-Indoor',
            'market-outdoor': 'Market-Outdoor',
            'marsh': 'Marsh',
            'martial_arts_gym': 'MartialArtsGym',
            'mausoleum': 'Mausoleum',
            'medina': 'Medina',
            'mezzanine': 'Mezzanine',
            'moat-water': 'Moat-Water',
            'mosque-outdoor': 'Mosque-Outdoor',
            'motel': 'Motel',
            'mountain': 'Mountain',
            'mountain_path': 'MountainPath',
            'mountain_snowy': 'MountainSnowy',
            'movie_theater-indoor': 'MovieTheater-Indoor',
            'museum-indoor': 'Museum-Indoor',
            'museum-outdoor': 'Museum-Outdoor',
            'music_studio': 'MusicStudio',
            'natural_history_museum': 'NaturalHistoryMuseum',
            'nursery': 'Nursery',
            'nursing_home': 'NursingHome',
            'oast_house': 'OastHouse',
            'ocean': 'Ocean',
            'office': 'Office',
            'office_building': 'OfficeBuilding',
            'office_cubicles': 'OfficeCubicles',
            'oilrig': 'Oilrig',
            'operating_room': 'OperatingRoom',
            'orchard': 'Orchard',
            'orchestra_pit': 'OrchestraPit',
            'pagoda': 'Pagoda',
            'palace': 'Palace',
            'pantry': 'Pantry',
            'park': 'Park',
            'parking_garage-indoor': 'ParkingGarage-Indoor',
            'parking_garage-outdoor': 'ParkingGarage-Outdoor',
            'parking_lot': 'ParkingLot',
            'pasture': 'Pasture',
            'patio': 'Patio',
            'pavilion': 'Pavilion',
            'pet_shop': 'PetShop',
            'pharmacy': 'Pharmacy',
            'phone_booth': 'PhoneBooth',
            'physics_laboratory': 'PhysicsLaboratory',
            'picnic_area': 'PicnicArea',
            'pier': 'Pier',
            'pizzeria': 'Pizzeria',
            'playground': 'Playground',
            'playroom': 'Playroom',
            'plaza': 'Plaza',
            'pond': 'Pond',
            'porch': 'Porch',
            'promenade': 'Promenade',
            'pub-indoor': 'Pub-Indoor',
            'racecourse': 'Racecourse',
            'raceway': 'Raceway',
            'raft': 'Raft',
            'railroad_track': 'RailroadTrack',
            'rainforest': 'Rainforest',
            'reception': 'Reception',
            'recreation_room': 'RecreationRoom',
            'repair_shop': 'RepairShop',
            'residential_neighborhood': 'ResidentialNeighborhood',
            'restaurant': 'Restaurant',
            'restaurant_kitchen': 'RestaurantKitchen',
            'restaurant_patio': 'RestaurantPatio',
            'rice_paddy': 'RicePaddy',
            'river': 'River',
            'rock_arch': 'RockArch',
            'roof_garden': 'RoofGarden',
            'rope_bridge': 'RopeBridge',
            'ruin': 'Ruin',
            'runway': 'Runway',
            'sandbox': 'Sandbox',
            'sauna': 'Sauna',
            'schoolhouse': 'Schoolhouse',
            'science_museum': 'ScienceMuseum',
            'server_room': 'ServerRoom',
            'shed': 'Shed',
            'shoe_shop': 'ShoeShop',
            'shopfront': 'Shopfront',
            'shopping_mall-indoor': 'ShoppingMall-Indoor',
            'shower': 'Shower',
            'ski_resort': 'SkiResort',
            'ski_slope': 'SkiSlope',
            'sky': 'Sky',
            'skyscraper': 'Skyscraper',
            'slum': 'Slum',
            'snowfield': 'Snowfield',
            'soccer_field': 'SoccerField',
            'stable': 'Stable',
            'stadium-baseball': 'Stadium-Baseball',
            'stadium-football': 'Stadium-Football',
            'stadium-soccer': 'Stadium-Soccer',
            'stage-indoor': 'Stage-Indoor',
            'stage-outdoor': 'Stage-Outdoor',
            'staircase': 'Staircase',
            'storage_room': 'StorageRoom',
            'street': 'Street',
            'subway_station-platform': 'SubwayStation-Platform',
            'supermarket': 'Supermarket',
            'sushi_bar': 'SushiBar',
            'swamp': 'Swamp',
            'swimming_hole': 'SwimmingHole',
            'swimming_pool-indoor': 'SwimmingPool-Indoor',
            'swimming_pool-outdoor': 'SwimmingPool-Outdoor',
            'synagogue-outdoor': 'Synagogue-Outdoor',
            'television_room': 'TelevisionRoom',
            'television_studio': 'TelevisionStudio',
            'temple-asia': 'Temple-Asia',
            'throne_room': 'ThroneRoom',
            'ticket_booth': 'TicketBooth',
            'topiary_garden': 'TopiaryGarden',
            'tower': 'Tower',
            'toyshop': 'Toyshop',
            'train_interior': 'TrainInterior',
            'train_station-platform': 'TrainStation-Platform',
            'tree_farm': 'TreeFarm',
            'tree_house': 'TreeHouse',
            'trench': 'Trench',
            'tundra': 'Tundra',
            'underwater-ocean_deep': 'Underwater-OceanDeep',
            'utility_room': 'UtilityRoom',
            'valley': 'Valley',
            'vegetable_garden': 'VegetableGarden',
            'veterinarians_office': 'VeterinariansOffice',
            'viaduct': 'Viaduct',
            'village': 'Village',
            'vineyard': 'Vineyard',
            'volcano': 'Volcano',
            'volleyball_court-outdoor': 'VolleyballCourt-Outdoor',
            'waiting_room': 'WaitingRoom',
            'water_park': 'WaterPark',
            'water_tower': 'WaterTower',
            'waterfall': 'Waterfall',
            'watering_hole': 'WateringHole',
            'wave': 'Wave',
            'wet_bar': 'WetBar',
            'wheat_field': 'WheatField',
            'wind_farm': 'WindFarm',
            'windmill': 'Windmill',
            'yard': 'Yard',
            'youth_hostel': 'YouthHostel',
            'zen_garden': 'ZenGarden'
 }
